#offset_time = OT - tankplayer_starttime
offset_time: 7.53
# Where is the tankfile:
ew_dir: '/home/mhagerty/run_playback/run_earthworm/params'
tankfile: "tankplayer.d.maule"
# Where is the starting SA.xml file:
SA_file: './SA.xml'
# Where should the modified SA.xml file be put:
#   (presumably where gfast_eew can find it)
#xmldir_out: '/home/mhagerty/run_playback/run_GFAST/maule/events'
xmldir_out: '/home/mhagerty/test'
